ft(design): home page design
sezeranoJchrisostome/crispy-t pull request #2
Opened 2022-09-15 21:55 UTC by sezeranoJchrisostome

# PR Description

This Pull Request aims to add design for the landing page of the Medical core

# Description of what this task covered

[ ] CSS and HTML only
[ ] BEM methodology

# How has this been tested?

1. Clone the repo
4. Navigate into crispy-t 
3. Check out to the appropriate branch(ft/design-home-page)
4. Open index.html in your browser on you can you live server extension

# Screenshots (If appropriate/applicable)
<img width="960" alt="2022-09-15" src="https://user-images.githubusercontent.com/56281095/190515482-7be0e1e8-1470-4160-addd-182b8990b441.png">

<img width="960" alt="2022-09-15 (3)" src="https://user-images.githubusercontent.com/56281095/190515506-9bbb3a55-70e0-4993-967d-3fdb6197f53a.png">

<img width="960" alt="2022-09-15 (1)" src="https://user-images.githubusercontent.com/56281095/190515547-28e7d3b7-6ecd-4244-a2fd-7d7e6ac34734.png">

<img width="960" alt="2022-09-15 (2)" src="https://user-images.githubusercontent.com/56281095/190515524-a6fb60cd-ccab-40bb-9b0d-a3da1134017d.png">

2022-09-17 18:07 UTC, serapieTuyishime commented on index.html
> +            <ul class="nav-link" >
great job making the list a block!

2022-09-17 18:09 UTC, serapieTuyishime commented on index.html
> +            <div class="site-heading site-heading--color-main site-heading--spaced">Meet our Experts</div>
i don't think the site heading should be  a block

2022-09-17 18:25 UTC, serapieTuyishime requested changes
Not much to change!

2022-09-17 18:25 UTC, serapieTuyishime commented on index.html
> +            <div class="card card__size-small card--shadow card--rounded">
not a good naming : .card__size-small     size-small is not a good name to give an element.

or did you accidentally make it an element  instead of a modifier

2022-09-17 18:25 UTC, serapieTuyishime commented on index.html
> +            <div class="card card__size-small card--shadow card--rounded">
same here

2022-09-17 18:25 UTC, serapieTuyishime commented on index.html
> +                    <svg width="23" height="23" viewBox="0 0 23 23" fill="none" xmlns="http://www.w3.org/2000/svg">
why a lot of lines for just 3 icons??, why not import the pictures from figma or just use Fa-fa 🤷‍♀️🤷‍♀️

-------P.S Not a review -----

2022-09-17 18:25 UTC, serapieTuyishime commented on index.html
> +    <div class="footer footer--full footer--secondary footer--alignment-center">
too much modifiers when a footer is just going to be used once!

2022-09-17 18:25 UTC, serapieTuyishime commented on index.html
> +        <form class="newsletter newsletter--size-full newsletter--position-astray newsletter--align-center">
modifiers

2022-09-17 18:25 UTC, serapieTuyishime commented on styles/main.css
> +.navigation__button {
you can just delete this since it is not styling anything anyway

2022-09-17 18:25 UTC, serapieTuyishime commented on styles/main.css
> +/* end newsletter */
Is it responsive without using the media queries?

2022-09-18 01:02 UTC, sezeranoJchrisostome commented on index.html
> +        <form class="newsletter newsletter--size-full newsletter--position-astray newsletter--align-center">
I did not get what you meant about modifiers please @serapieTuyishime

2022-09-18 01:05 UTC, sezeranoJchrisostome commented on index.html
> +                    <svg width="23" height="23" viewBox="0 0 23 23" fill="none" xmlns="http://www.w3.org/2000/svg">
I think we can use img tag because we are  restricted to use any CSS library

2022-09-18 01:13 UTC, sezeranoJchrisostome commented on index.html
> +            <div class="card card__size-small card--shadow card--rounded">
Oooh let me change.

2022-09-18 01:15 UTC, sezeranoJchrisostome commented on index.html
> +            <div class="card card__size-small card--shadow card--rounded">
Because they are the same card I think both have the same issue. I will work on that too

2022-09-18 06:23 UTC, alain-kubwayo reviewed
Excellent work! You adhered to BEM naming convention throughout the project. I have added some comments on the areas that need fine-tuning for your reference. Cheers!

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +            </div>
Excellent job following BEM naming convention!

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +        <img class="content__image" src="./assets/img/n.png" alt="" srcset="">
It's always a good practice to give images alt value in case the server can't display the image correctly.

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +                    <svg width="23" height="23" viewBox="0 0 23 23" fill="none" xmlns="http://www.w3.org/2000/svg">
You're right. Introducing Font Awesome would go against sticking to only HTML and CSS for the project. SVGs should be fine, I think.

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +                    Proffessional
You made a minor typo here and on the other cards as well. It should be `profession` instead of `proffessional`

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +                    Proffessional
Typo

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +    <div class="footer footer--full footer--secondary footer--alignment-center">
That's what I thought too.

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +        </div>
This looks okay but I would personally add `class="footer__text footer__text--gray"` to `<p>` tag to avoid introducing extra `<div>` unnecessarily

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +            <input placeholder="Your Email" type="text" class="newsletter__field newsletter__field--text-medium newsletter__field--text-gray newsletter__field--size-full newsletter__field--rounded-le
Since you only have one input throughout your application, I think there are way too many modifiers for that. A lot of the styles could be added to the element `newsletter__field` for simplicity.

2022-09-18 06:23 UTC, alain-kubwayo commented on index.html
> +            <button type="submit" class="newsletter__button newsletter__button--color-success newsletter__button--rounded-right">Subscribe</button>
I believe you can reuse the `login` or `join us` block for this instead of creating a brand new button from scratch.

2022-09-18 06:23 UTC, alain-kubwayo commented on styles/main.css
> +.navigation__button {
Good idea Serapie!

2022-09-18 14:21 UTC, sezeranoJchrisostome commented on index.html
> +            <button type="submit" class="newsletter__button newsletter__button--color-success newsletter__button--rounded-right">Subscribe</button>
Thank you! @alain-kubwayo, I will try to reuse it and I will let you know if it going going to work for me

2022-09-18 14:47 UTC, sezeranoJchrisostome commented on index.html
> +            </div>
Thank you! @alain-kubwayo

2022-09-18 18:47 UTC, serapieTuyishime approved these changes
Well done mate!

2022-09-19 09:57 UTC, alain-kubwayo approved these changes
LGTM

2022-09-19 12:01 UTC, karemarsy commented on styles/main.css
> +.nav-link{
why did you create another class called `nav-link` while you already have `navigation`? you should use `nav-link` as an element of the `navigation` that would make sense

2022-09-19 12:01 UTC, karemarsy commented on styles/main.css
> +.card__image{
where does this class call `card` comes from?

2022-09-19 12:01 UTC, karemarsy commented on styles/main.css
> +.footer.footer--secondary {
That's not BEM

2022-09-19 12:01 UTC, karemarsy commented on styles/responsiveness.css
> +@media only screen and (max-width: 600px) {
why did you duplicate this media query you already have `@media only screen and (max-width: 600px)` above

2022-09-19 12:42 UTC, sezeranoJchrisostome commented on styles/main.css
> +.footer.footer--secondary {
I had confusion about that but now I will stick to the `footer--secondary`

2022-09-19 13:28 UTC, sezeranoJchrisostome commented on styles/responsiveness.css
> +@media only screen and (max-width: 600px) {
I was trying to put things together in my CSS, like content responsiveness alone  in it's media query, but now I can change to same media query since there the same

2022-09-19 13:39 UTC, sezeranoJchrisostome commented on styles/main.css
> +.card__image{
I defined it in `index.html` but I can try to add it in my CSS too but they will be not much style to add there.

2022-09-19 13:49 UTC, serapieTuyishime commented on styles/main.css
> +.card__image{
He resolved it

2022-09-19 13:52 UTC, serapieTuyishime commented on styles/main.css
> +.footer--secondary {
great change!

2022-09-19 13:54 UTC, serapieTuyishime approved these changes
Well resolved ✨

2022-09-19 13:54 UTC, serapieTuyishime commented on styles/main.css
> +.footer--secondary {
Great change!

2022-09-21 06:41 UTC, alain-kubwayo approved these changes
Good job applying @karemarsy feedback.

2022-09-21 06:41 UTC, alain-kubwayo commented on styles/main.css
> +.footer--secondary {
Well-done on applying requested changes.

2022-09-21 06:41 UTC, alain-kubwayo commented on index.html
> +                <li class="navigation__list__item">
I didn't know this kind of naming convention existed in BEM but well-done applying the changes per @karemarsy's feedback.

2022-09-21 09:31 UTC, sezeranoJchrisostome commented on index.html
> +                <li class="navigation__list__item">
Thank you @alain-kubwayo,
yesterday we had a session and we discussed about nesting elements and I saw the possibility of how this could be possible and I guess that here we have to be careful just in case we have many elements that are nested. 

@karemarsy

2022-09-22 10:17 UTC, karemarsy commented on styles/main.css
> +
remove the space here

2022-09-22 11:00 UTC, sezeranoJchrisostome commented on index.html
> +                <li class="navigation__list__item">
This type of nesting was allowed in the last version of BEM  but now is not supported and it is not good practice too, you can refer to this blog [Here](https://scalablecss.com/bem-nesting-grandchild-elements/), I also have updated myself to it

2022-09-27 12:36 UTC, sezeranoJchrisostome commented
Merging crisp landing page

2022-09-27 12:37 UTC, merged